"""
sync_headless_skills.py — Generate headless (non-interactive) versions of BMAD skills
for use by bmadder.sh and bmadder-iterative.sh pipeline scripts.

The BMAD skills in .agent/skills/ are designed for interactive IDE use — they have
menus, <ask> prompts, HALT conditions, and multi-file step architectures. The bmadder
pipeline scripts need these skills to run headlessly (non-interactive, auto-proceed).

This script:
  1. Reads source skills from .agent/skills/
  2. Inlines step files into consolidated documents
  3. Strips interactive elements (menus, <ask>, user-choice branches, HALTs)
  4. Prepends a headless-mode preamble
  5. Writes output to scripts/headless-skills/
  6. Creates a manifest.json for staleness detection

Usage:
  uv run scripts/sync_headless_skills.py           # Generate all headless skills
  uv run scripts/sync_headless_skills.py --check   # Verify output is up-to-date (CI)
  uv run scripts/sync_headless_skills.py --diff    # Show what would change
  uv run scripts/sync_headless_skills.py --verbose # Show stripping details

Run this after BMAD framework updates, or during bootstrap.
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / ".agent" / "skills"
OUTPUT_DIR = ROOT / "scripts" / "headless-skills"
MANIFEST_FILE = OUTPUT_DIR / "manifest.json"

GENERATOR_VERSION = "1.0.0"

# ============================================================================
# SKILL DEFINITIONS: which source files map to which output
# ============================================================================

SKILL_DEFINITIONS = {
    "sm-create-stories": {
        "description": "Scrum Master: bulk story creation from PRD",
        "sources": [
            "bmad-create-epics-and-stories/workflow.md",
            "bmad-create-epics-and-stories/steps/step-01-validate-prerequisites.md",
            "bmad-create-epics-and-stories/steps/step-02-design-epics.md",
            "bmad-create-epics-and-stories/steps/step-03-create-stories.md",
            "bmad-create-epics-and-stories/steps/step-04-final-validation.md",
        ],
        "extras": [
            "bmad-create-story/checklist.md",
            "bmad-create-story/template.md",
        ],
    },
    "sm-create-story": {
        "description": "Scrum Master: single story creation",
        "sources": [
            "bmad-create-story/workflow.md",
            "bmad-create-story/discover-inputs.md",
        ],
        "extras": [
            "bmad-create-story/checklist.md",
            "bmad-create-story/template.md",
        ],
    },
    "po-review": {
        "description": "Product Owner: story quality review gate",
        "sources": [
            "bmad-create-story/checklist.md",
        ],
        "extras": [],
    },
    "dev-story": {
        "description": "Developer: story implementation (TDD, red-green-refactor)",
        "sources": [
            "bmad-dev-story/workflow.md",
        ],
        "extras": [],
    },
    "qa-review": {
        "description": "QA Auditor: code review and acceptance verification",
        "sources": [
            "bmad-code-review/workflow.md",
            "bmad-code-review/steps/step-01-gather-context.md",
            "bmad-code-review/steps/step-02-review.md",
            "bmad-code-review/steps/step-03-triage.md",
            "bmad-code-review/steps/step-04-present.md",
        ],
        "extras": [],
    },
}


# ============================================================================
# HEADLESS PREAMBLE
# ============================================================================

def make_preamble(skill_name: str, description: str, source_files: list[str]) -> str:
    sources_list = "\n".join(f"#   - .agent/skills/{s}" for s in source_files)
    return f"""<!-- ====================================================================== -->
<!-- GENERATED FILE — DO NOT EDIT MANUALLY                                  -->
<!-- Source: .agent/skills/ (see manifest.json for exact files)              -->
<!-- Generated by: scripts/sync_headless_skills.py v{GENERATOR_VERSION}               -->
<!-- Re-run after BMAD updates: uv run scripts/sync_headless_skills.py      -->
<!-- ====================================================================== -->
# Headless Skill: {skill_name}

**{description}**

## HEADLESS MODE DIRECTIVES

- This is a consolidated, non-interactive version of the BMAD skill.
- All menus, user prompts, HALT conditions, and step-file loading have been stripped.
- Auto-proceed through all steps without waiting for input.
- Context documents are provided by the pipeline orchestrator, not config.yaml.
- If you encounter residual interactive instructions, IGNORE them and auto-proceed.

# Source files consolidated:
{sources_list}

---

"""


# ============================================================================
# STRIPPING ENGINE
# ============================================================================

# Patterns that indicate a line is part of interactive-only content
INTERACTIVE_LINE_PATTERNS = [
    # <ask> tags
    re.compile(r"^\s*<ask>.*</ask>\s*$"),
    # HALT actions (user-interaction type, not error type)
    re.compile(r"^\s*<action>HALT\s*-\s*(No work needed|User needs to|Run [\w-]+ to)\b"),
    re.compile(r"^\s*<action>HALT\s*$"),
    re.compile(r"^\s*<action>HALT\s*</action>\s*$"),
    # Menu display instructions
    re.compile(r"^\s*Display:\s*`\*\*.*\[C\].*Continue"),
    re.compile(r"^\*\*HALT\*\*\s*—\s*I am waiting for your choice"),
    # "wait for user" directives
    re.compile(r".*(?:halt and wait for user|ALWAYS halt and wait for user|Wait for user selection|Wait for user confirmation).*", re.IGNORECASE),
    # Step-file loading directives (content is already inlined)
    re.compile(r"^\s*(?:Read fully and follow|read fully and follow|Load, read completely, then execute|then read fully and follow):\s*`?\./(?:steps|steps-[a-z])/"),
    re.compile(r".*ONLY WHEN C is selected.*read fully and follow.*"),
    # Config.yaml loading (orchestrator provides context)
    re.compile(r"^\s*(?:\d+\.\s*)?Load config from\s*`?\{project-root\}/_bmad/bmm/config\.yaml"),
]

# Block-level patterns: remove entire <check if="user chooses...">...</check> blocks
INTERACTIVE_BLOCK_START = re.compile(
    r'^\s*<check\s+if="(?:user chooses|user provides|user input)',
    re.IGNORECASE,
)

# Lines that signal "this section is about menus" - remove the whole section
MENU_SECTION_HEADERS = [
    "### 10. Present MENU OPTIONS",
    "#### Menu Handling Logic:",
    "#### EXECUTION RULES:",
]

# YAML frontmatter (between --- markers at start of file)
FRONTMATTER_PATTERN = re.compile(r"^---\s*$")

# Patterns to clean up but not remove entirely
CLEANUP_PATTERNS = [
    # Convert remaining HALT-on-error to descriptive skip
    (
        re.compile(r"<action\s*(?:if=\"[^\"]*\")?>HALT:?\s*\"?([^\"<]+)\"?\s*</action>"),
        r"<!-- HEADLESS: Error condition - \1 -->",
    ),
    # Remove "NEVER generate content without user input" (headless auto-generates)
    (
        re.compile(r".*🛑 NEVER generate content without user input.*"),
        "",
    ),
    # Clean "FORBIDDEN to load next step until user selects" 
    (
        re.compile(r".*FORBIDDEN to load next step until user selects.*"),
        "",
    ),
    # Clean "ONLY proceed to next step when user selects 'C'"
    (
        re.compile(r".*ONLY proceed to next step when user selects 'C'.*"),
        "",
    ),
    # Clean "User can chat or ask questions"
    (
        re.compile(r".*User can chat or ask questions.*"),
        "",
    ),
]


def strip_frontmatter(content: str) -> str:
    """Remove YAML frontmatter (--- ... ---) from the start of content."""
    lines = content.split("\n")
    if not lines or lines[0].strip() != "---":
        return content
    # Find closing ---
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[i + 1:])
    return content  # No closing ---, return as-is


def strip_interactive_blocks(content: str, verbose: bool = False) -> str:
    """Remove interactive blocks (<check if="user chooses...">...</check>)."""
    lines = content.split("\n")
    result = []
    skip_depth = 0
    stripped_blocks = 0

    for line in lines:
        # Check if we're entering an interactive block
        if INTERACTIVE_BLOCK_START.search(line):
            skip_depth += 1
            stripped_blocks += 1
            continue

        # Track nesting within skipped blocks
        if skip_depth > 0:
            if "<check " in line and "if=" in line:
                skip_depth += 1
            elif "</check>" in line:
                skip_depth -= 1
            continue

        result.append(line)

    if verbose and stripped_blocks > 0:
        print(f"    Stripped {stripped_blocks} interactive <check> block(s)")

    return "\n".join(result)


def strip_interactive_lines(content: str, verbose: bool = False) -> str:
    """Remove individual interactive lines."""
    lines = content.split("\n")
    result = []
    stripped_count = 0

    for line in lines:
        matched = False
        for pattern in INTERACTIVE_LINE_PATTERNS:
            if pattern.match(line) or pattern.search(line):
                stripped_count += 1
                matched = True
                break
        if not matched:
            result.append(line)

    if verbose and stripped_count > 0:
        print(f"    Stripped {stripped_count} interactive line(s)")

    return "\n".join(result)


def strip_menu_sections(content: str, verbose: bool = False) -> str:
    """Remove entire menu sections (header + content until next ## or ###)."""
    lines = content.split("\n")
    result = []
    in_menu_section = False
    menu_level = 0
    stripped_sections = 0

    for line in lines:
        # Check if this line starts a menu section
        if any(header in line for header in MENU_SECTION_HEADERS):
            in_menu_section = True
            # Determine heading level
            menu_level = len(line) - len(line.lstrip("#"))
            stripped_sections += 1
            continue

        # If in a menu section, skip until we hit a heading of same or higher level
        if in_menu_section:
            if line.startswith("#"):
                current_level = len(line) - len(line.lstrip("#"))
                if current_level <= menu_level:
                    in_menu_section = False
                    result.append(line)
                    continue
            continue

        result.append(line)

    if verbose and stripped_sections > 0:
        print(f"    Stripped {stripped_sections} menu section(s)")

    return "\n".join(result)


def apply_cleanup_patterns(content: str, verbose: bool = False) -> str:
    """Apply regex replacements for cleanup patterns."""
    cleaned = 0
    for pattern, replacement in CLEANUP_PATTERNS:
        new_content = pattern.sub(replacement, content)
        if new_content != content:
            cleaned += 1
        content = new_content

    if verbose and cleaned > 0:
        print(f"    Applied {cleaned} cleanup pattern(s)")

    return content


def collapse_blank_lines(content: str) -> str:
    """Collapse runs of 3+ blank lines down to 2."""
    return re.sub(r"\n{4,}", "\n\n\n", content)


def strip_all(content: str, verbose: bool = False) -> str:
    """Apply all stripping transformations."""
    content = strip_frontmatter(content)
    content = strip_interactive_blocks(content, verbose)
    content = strip_interactive_lines(content, verbose)
    content = strip_menu_sections(content, verbose)
    content = apply_cleanup_patterns(content, verbose)
    content = collapse_blank_lines(content)
    return content.strip() + "\n"


# ============================================================================
# FILE OPERATIONS
# ============================================================================

def read_skill_file(rel_path: str) -> str:
    """Read a source skill file, return its content."""
    path = SKILLS_DIR / rel_path
    if not path.exists():
        print(f"  [WARN] Source file not found: {rel_path}")
        return ""
    return path.read_text(encoding="utf-8")


def file_hash(path: Path) -> str:
    """SHA256 hash of a file's content."""
    if not path.exists():
        return ""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_hash(rel_path: str) -> str:
    """SHA256 hash of a source skill file."""
    return file_hash(SKILLS_DIR / rel_path)


def build_skill(name: str, defn: dict, verbose: bool = False) -> str:
    """Build a consolidated headless skill file from its definition."""
    all_sources = defn["sources"] + defn.get("extras", [])

    if verbose:
        print(f"  Building {name}.md from {len(all_sources)} source file(s)")

    # Preamble
    output = make_preamble(name, defn["description"], all_sources)

    # Main source files
    for rel_path in defn["sources"]:
        content = read_skill_file(rel_path)
        if not content:
            continue
        if verbose:
            print(f"    Processing: {rel_path}")
        content = strip_all(content, verbose)
        output += f"\n<!-- Source: {rel_path} -->\n\n"
        output += content
        output += "\n\n"

    # Extra files (checklists, templates) — appended as reference sections
    extras = defn.get("extras", [])
    if extras:
        output += "\n---\n\n# Reference Materials\n\n"
        for rel_path in extras:
            content = read_skill_file(rel_path)
            if not content:
                continue
            if verbose:
                print(f"    Processing extra: {rel_path}")
            content = strip_frontmatter(content)
            content = collapse_blank_lines(content)
            output += f"<!-- Source: {rel_path} -->\n\n"
            output += content.strip()
            output += "\n\n"

    return output


def build_manifest(outputs: dict[str, str]) -> dict:
    """Build a manifest recording source hashes and generation metadata."""
    manifest = {
        "generator_version": GENERATOR_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "skills": {},
    }

    for name, defn in SKILL_DEFINITIONS.items():
        all_sources = defn["sources"] + defn.get("extras", [])
        manifest["skills"][name] = {
            "description": defn["description"],
            "output_file": f"{name}.md",
            "sources": {
                rel_path: source_hash(rel_path)
                for rel_path in all_sources
            },
            "output_hash": hashlib.sha256(
                outputs[name].encode("utf-8")
            ).hexdigest(),
        }

    return manifest


# ============================================================================
# CLI COMMANDS
# ============================================================================

def cmd_generate(verbose: bool = False) -> bool:
    """Generate all headless skill files."""
    print()
    print("=== Sync Headless Skills ===")
    print()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    outputs = {}
    for name, defn in SKILL_DEFINITIONS.items():
        outputs[name] = build_skill(name, defn, verbose)

    # Write output files
    for name, content in outputs.items():
        out_path = OUTPUT_DIR / f"{name}.md"
        out_path.write_text(content, encoding="utf-8")
        lines = content.count("\n")
        print(f"  [OK] {name}.md ({lines} lines)")

    # Write manifest
    manifest = build_manifest(outputs)
    MANIFEST_FILE.write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(f"  [OK] manifest.json")

    print()
    print(f"Generated {len(outputs)} headless skill files in scripts/headless-skills/")
    print()
    return True


def cmd_check() -> bool:
    """Check if generated files are up-to-date with source skills."""
    print()
    print("=== Checking Headless Skills Freshness ===")
    print()

    if not MANIFEST_FILE.exists():
        print("  [STALE] No manifest.json found — run sync_headless_skills.py to generate")
        return False

    manifest = json.loads(MANIFEST_FILE.read_text(encoding="utf-8"))
    stale = False

    for name, info in manifest.get("skills", {}).items():
        out_path = OUTPUT_DIR / info["output_file"]
        if not out_path.exists():
            print(f"  [STALE] {info['output_file']} — missing")
            stale = True
            continue

        for rel_path, recorded_hash in info.get("sources", {}).items():
            current = source_hash(rel_path)
            if current != recorded_hash:
                print(f"  [STALE] {name}.md — source changed: {rel_path}")
                stale = True
                break
        else:
            print(f"  [OK]    {name}.md")

    print()
    if stale:
        print("Headless skills are STALE. Run: uv run scripts/sync_headless_skills.py")
        print()
        return False
    else:
        print("All headless skills are up-to-date.")
        print()
        return True


def cmd_diff(verbose: bool = False) -> bool:
    """Show what would change if regenerated."""
    print()
    print("=== Headless Skills Diff ===")
    print()

    has_changes = False
    for name, defn in SKILL_DEFINITIONS.items():
        new_content = build_skill(name, defn, verbose)
        out_path = OUTPUT_DIR / f"{name}.md"

        if not out_path.exists():
            print(f"  [NEW]     {name}.md ({new_content.count(chr(10))} lines)")
            has_changes = True
            continue

        old_content = out_path.read_text(encoding="utf-8")
        if old_content == new_content:
            print(f"  [SAME]    {name}.md")
        else:
            old_lines = old_content.count("\n")
            new_lines = new_content.count("\n")
            print(f"  [CHANGED] {name}.md ({old_lines} → {new_lines} lines)")
            has_changes = True

    print()
    if has_changes:
        print("Run without --diff to apply changes.")
    else:
        print("No changes needed.")
    print()
    return not has_changes


# ============================================================================
# MAIN
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate headless (non-interactive) BMAD skills for pipeline scripts."
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Check if generated files are up-to-date (exit 1 if stale)"
    )
    parser.add_argument(
        "--diff", action="store_true",
        help="Show what would change without writing files"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Show detailed stripping information"
    )
    args = parser.parse_args()

    # Verify skills directory exists
    if not SKILLS_DIR.exists():
        print(f"[ERROR] Skills directory not found: {SKILLS_DIR}")
        print("Are you running from the bmadder-framework root?")
        sys.exit(1)

    if args.check:
        ok = cmd_check()
        sys.exit(0 if ok else 1)
    elif args.diff:
        cmd_diff(args.verbose)
    else:
        cmd_generate(args.verbose)


if __name__ == "__main__":
    main()
